package view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class FrView extends javax.swing.JFrame {

    /**
     * Creates new form FrView
     */
    public FrView() {
        initComponents();
        initComponentsManually();
        initEvent();
    }
    
    private void initComponentsManually(){
        setLocationRelativeTo(null);
        setTitle("LINGOES");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Image avatarImage = new ImageIcon(getClass().getResource("/images/avatar.png")).getImage();
        setIconImage(avatarImage);
        Image image = new ImageIcon(getClass().getResource("/images/back.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(image);
        btnBack.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/next.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnNext.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/menu.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnLanguage.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/down.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnDown.setIcon(icon);
        btnDown.setBackground(new Color(0, 0, 0, 0));
        btnSearchMore.setIcon(icon);
        btnDown.setBackground(new Color(0, 0, 0, 0));
        image = new ImageIcon(getClass().getResource("/images/right.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnRight.setIcon(icon);
        btnRight.setBackground(new Color(0, 0, 0, 0));
        image = new ImageIcon(getClass().getResource("/images/search.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnSearch.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/list.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnMenu.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/hide.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnHide.setIcon(icon);
        image = new ImageIcon(getClass().getResource("/images/sound.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnSound.setIcon(icon);
        btnSound.setBackground(new Color(0, 0, 0, 0));
        image = new ImageIcon(getClass().getResource("/images/book.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnTranslate.setIcon(icon);
        btnTranslate.setBackground(new Color(0, 0, 0, 0));
        image = new ImageIcon(getClass().getResource("/images/home.png"))
                            .getImage()
                            .getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image);
        btnHome.setIcon(icon);
        btnHome.setBackground(new Color(0, 0, 0, 0));
    }
    
    private void initEvent(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnInput = new javax.swing.JPanel();
        btnLanguage = new javax.swing.JButton();
        tfInput = new javax.swing.JTextField();
        btnDown = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        pnSearch = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchMore = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        pnRight = new javax.swing.JPanel();
        pnRightBottom = new javax.swing.JPanel();
        pnRightTop = new javax.swing.JPanel();
        btnHide = new javax.swing.JButton();
        btnSound = new javax.swing.JButton();
        btnTranslate = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(230, 45));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        pnTop.setPreferredSize(new java.awt.Dimension(775, 45));

        btnBack.setAlignmentY(0.0F);
        btnBack.setFocusPainted(false);
        btnBack.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBack.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBack.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBack.setPreferredSize(new java.awt.Dimension(25, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnTop.add(btnBack);

        btnNext.setAlignmentY(0.0F);
        btnNext.setFocusPainted(false);
        btnNext.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNext.setMaximumSize(new java.awt.Dimension(25, 25));
        btnNext.setMinimumSize(new java.awt.Dimension(25, 25));
        btnNext.setPreferredSize(new java.awt.Dimension(25, 25));
        pnTop.add(btnNext);

        pnInput.setBackground(new java.awt.Color(255, 255, 255));

        btnLanguage.setBackground(new java.awt.Color(0, 0, 0));
        btnLanguage.setAlignmentY(0.0F);
        btnLanguage.setFocusPainted(false);
        btnLanguage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLanguage.setMaximumSize(new java.awt.Dimension(25, 25));
        btnLanguage.setMinimumSize(new java.awt.Dimension(25, 25));
        btnLanguage.setPreferredSize(new java.awt.Dimension(25, 25));
        pnInput.add(btnLanguage);

        tfInput.setMinimumSize(new java.awt.Dimension(50, 25));
        tfInput.setPreferredSize(new java.awt.Dimension(350, 25));
        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        pnInput.add(tfInput);

        btnDown.setBackground(new java.awt.Color(0, 0, 0));
        btnDown.setAlignmentY(0.0F);
        btnDown.setFocusPainted(false);
        btnDown.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDown.setMaximumSize(new java.awt.Dimension(25, 25));
        btnDown.setMinimumSize(new java.awt.Dimension(25, 25));
        btnDown.setPreferredSize(new java.awt.Dimension(25, 25));
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });
        pnInput.add(btnDown);

        btnRight.setBackground(new java.awt.Color(0, 0, 0));
        btnRight.setAlignmentY(0.0F);
        btnRight.setFocusPainted(false);
        btnRight.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRight.setMaximumSize(new java.awt.Dimension(25, 25));
        btnRight.setMinimumSize(new java.awt.Dimension(25, 25));
        btnRight.setPreferredSize(new java.awt.Dimension(25, 25));
        pnInput.add(btnRight);

        pnTop.add(pnInput);

        pnSearch.setBackground(new java.awt.Color(255, 255, 255));

        tfSearch.setMinimumSize(new java.awt.Dimension(30, 25));
        tfSearch.setPreferredSize(new java.awt.Dimension(150, 25));
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        pnSearch.add(tfSearch);

        btnSearch.setAlignmentY(0.0F);
        btnSearch.setFocusPainted(false);
        btnSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearch.setMaximumSize(new java.awt.Dimension(25, 25));
        btnSearch.setMinimumSize(new java.awt.Dimension(25, 25));
        btnSearch.setPreferredSize(new java.awt.Dimension(25, 25));
        pnSearch.add(btnSearch);

        btnSearchMore.setBackground(new java.awt.Color(0, 0, 0));
        btnSearchMore.setAlignmentY(0.0F);
        btnSearchMore.setFocusPainted(false);
        btnSearchMore.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearchMore.setMaximumSize(new java.awt.Dimension(25, 25));
        btnSearchMore.setMinimumSize(new java.awt.Dimension(25, 25));
        btnSearchMore.setPreferredSize(new java.awt.Dimension(25, 25));
        btnSearchMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMoreActionPerformed(evt);
            }
        });
        pnSearch.add(btnSearchMore);

        pnTop.add(pnSearch);

        btnMenu.setAlignmentY(0.0F);
        btnMenu.setFocusPainted(false);
        btnMenu.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMenu.setMaximumSize(new java.awt.Dimension(25, 25));
        btnMenu.setMinimumSize(new java.awt.Dimension(25, 25));
        btnMenu.setPreferredSize(new java.awt.Dimension(25, 25));
        pnTop.add(btnMenu);

        getContentPane().add(pnTop, java.awt.BorderLayout.NORTH);

        pnMain.setLayout(new java.awt.BorderLayout());

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setMinimumSize(new java.awt.Dimension(150, 0));
        pnLeft.setPreferredSize(new java.awt.Dimension(150, 468));

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        pnMain.add(pnLeft, java.awt.BorderLayout.WEST);

        pnRight.setLayout(new java.awt.BorderLayout());

        pnRightBottom.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pnRightBottomLayout = new javax.swing.GroupLayout(pnRightBottom);
        pnRightBottom.setLayout(pnRightBottomLayout);
        pnRightBottomLayout.setHorizontalGroup(
            pnRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        pnRightBottomLayout.setVerticalGroup(
            pnRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pnRight.add(pnRightBottom, java.awt.BorderLayout.CENTER);

        pnRightTop.setPreferredSize(new java.awt.Dimension(625, 45));

        btnHide.setFocusPainted(false);
        btnHide.setLabel("");
        btnHide.setMaximumSize(new java.awt.Dimension(20, 20));
        btnHide.setMinimumSize(new java.awt.Dimension(20, 20));
        btnHide.setPreferredSize(new java.awt.Dimension(20, 20));

        btnSound.setFocusPainted(false);
        btnSound.setMaximumSize(new java.awt.Dimension(30, 20));
        btnSound.setMinimumSize(new java.awt.Dimension(30, 20));
        btnSound.setPreferredSize(new java.awt.Dimension(30, 20));

        btnTranslate.setText("Text Translation");
        btnTranslate.setFocusPainted(false);
        btnTranslate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnTranslate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTranslate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTranslate.setMaximumSize(new java.awt.Dimension(20, 200));
        btnTranslate.setMinimumSize(new java.awt.Dimension(50, 20));
        btnTranslate.setPreferredSize(new java.awt.Dimension(50, 20));

        btnHome.setText("Start Page");
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHome.setMaximumSize(new java.awt.Dimension(20, 200));
        btnHome.setMinimumSize(new java.awt.Dimension(50, 20));
        btnHome.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout pnRightTopLayout = new javax.swing.GroupLayout(pnRightTop);
        pnRightTop.setLayout(pnRightTopLayout);
        pnRightTopLayout.setHorizontalGroup(
            pnRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        pnRightTopLayout.setVerticalGroup(
            pnRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnRight.add(pnRightTop, java.awt.BorderLayout.NORTH);

        pnMain.add(pnRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMoreActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLanguage;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchMore;
    private javax.swing.JButton btnSound;
    private javax.swing.JButton btnTranslate;
    private javax.swing.JPanel pnInput;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnRightBottom;
    private javax.swing.JPanel pnRightTop;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JPanel pnTop;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
